### ISSUE TITLE
Compute size button doesn't handle releases with no data

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#440]
![Screenshot 2023-07-28 at 2 49 22 pm](https://github.com/umccr/elsa-data/assets/1973827/972ef75b-0d34-4906-969d-1e306332e7f4)

In a case like this - where for whatever reason no files are in the manifest (no specimens / no location selected etc) - the compute size button causes an exception to be thrown in the manifest generator - and nothing else happens in the UI.

I don't think we need to do much here - but I think if the manifest generator fails due to one of these exceptions - I think the compute TRPC call can catch that exception - and just return back a total size of 0 bytes (and 0 files).

**Comment by andrewpatto** [comment]
```
[14:48:46.711] ERROR (elsa-data/78924): Cannot activate this release because as currently configured no data would actually be contained in the release
    err: {
      "type": "ReleaseActivatedNothingError",
      "message": "Cannot activate this release because as currently configured no data would actually be contained in the release",
      "stack":
          ReleaseActivatedNothingError: Cannot activate this release because as currently configured no data would actually be contained in the release
              at transformDbManifestToMasterManifest (/Users//Work/UMCCR/elsa-data/application/backend/src/business/services/manifests/manifest-master-helper.ts:62:11)
              at ManifestService.createMasterManifest (/Users//Work/UMCCR/elsa-data/application/backend/src/business/services/manifests/manifest-service.ts:99:47)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async ManifestService.computeReleaseSize (/Users//Work/UMCCR/elsa-data/application/backend/src/business/services/manifests/manifest-service.ts:116:48)
              at async /Users//Work/UMCCR/elsa-data/application/backend/src/api/routes/internal-trpc/manifest-routes.ts:14:14
              at async resolveMiddleware (/Users//Work/UMCCR/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:418:30)
              at async callRecursive (/Users//Work/UMCCR/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:454:32)
              at async next (/Users//Work/UMCCR/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:462:32)
              at async callRecursive (/Users//Work/UMCCR/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:454:32)
              at async next (/Users//Work/UMCCR/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:462:32)
      "detail": "No data locations enabled",
      "name": "ReleaseActivatedNothingError"
    }
```
